### ISSUE TITLE
6.1.1	Create Azure account

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/test-installation-documentation#10]
Add details on how to create Account.
If specific account type should used and suggestions on free account usage.

**Comment by MaNe2020** [comment]
@GINAGC this section is still missing details. 
I will add v0.2 label.
Please move it to correct pipeline stage. 

Recommended steps:

1. Navigate to: [Microsoft Azure](https://azure.microsoft.com/en-us/free/) and click on "Start Free"
2. You will be prompt to sign in with Microsoft account. If you have one, use it to sign in, if not click on to "create new" Microsoft account
3. Once you sign with Microsoft account, follow the steps to create free Azure account.
4. Once created you can access Azure account via: [Azure Portal](https://portal.azure.com/)

**Comment by Kirsten-Osborn** [comment]
@MaNe2020 @GINAGC we've decided to handle this as a pre-req, and not provide instructions on how to set up an azure account in the installation guide - I've updated section 6.1 in v0.3.  So this issue can be closed.
