### ISSUE TITLE
6.1.2	Create user account for person completing the installation

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/test-installation-documentation#12]
Add details to this section.
Or if GW account is going to be used, add explanation to that (how it gets provided).

**Comment by MaNe2020** [comment]
@GINAGC changed label to v0.2

"Create user account" for what?
If 6.1.1 states create Azure account.
Please add details as to what needs to be created.

**Comment by Kirsten-Osborn** [comment]
@MaNe2020 @GINAGC this is now being handled as a pre-req - section 6.1 has been updated in v0.3 to remind the operator that all azure pre-reqs should be in place.  This issue can be closed.
