### ISSUE TITLE
6.3.2	Create Azure Storage to store terraform remote state in terraform-remote-state

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/test-installation-documentation#16]
Add step for cloning the repo.

`git clone https://github.com/filetrust/Glasswall-ICAP-Platform.git`

**Comment by GINAGC** [comment]
Feedback from Samarth:

**Comment by GINAGC** [comment]
![103994585-354f7280-51bd-11eb-9724-3559eda4b73f](https://user-images.githubusercontent.com/70196799/104005763-e77b4000-51a5-11eb-80dc-929dd8599f7f.png)

**Comment by Lestat06** [comment]
![6 3 2](https://user-images.githubusercontent.com/6232283/104516759-21f53a80-55f5-11eb-9885-9f7ff6ca202f.PNG)

**Comment by GINAGC** [comment]
I am closing this as duplicated with https://github.com/k8-proxy/test-installation-documentation/issues/11 which has more information.
