### ISSUE TITLE
6.2.1 and 6.2.3

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/test-installation-documentation#18]
1. In first step python installation is using brew command but brew installation comes into picture in second step.So not valid.

2. Add a command to check python version. python -v to verify it is installed and symlinked. 

3. Missing bracket in
/bin/bash -c "$(curl -fsSL 
https://raw.githubusercontent.com/Homebrew/install/master/install.sh "

4. hyphen error, dint work when copy pasted,
            -replace brew –v with brew -v

5.  replace bash -version with proper hyphen(wrong hyphen)
6.Check for hyphen in - terraform –version 

7. Mac has xcode-select --install dependency to install home brew. Please mention it

**Comment by Kirsten-Osborn** [comment]
@samarthdd  
1. Order of python and Brew steps reversed in documentation v0.2
2. python -v step added to documentation v0.2
3. Missing ) added in documentation v0.2
4. hyphen updated in documentation v0.2
5. updated to bash --version in documentation v0.2
6. terraform -version hyphen updated in documentation v0.2
7. Explanation and Xcode installation step added in documentation v0.2

**Comment by samarthdd** [comment]
@Kirsten-Osborn 

6.2.1 say copy paste below command

![image](https://user-images.githubusercontent.com/64204445/104585456-09832f80-568a-11eb-9cde-28ef6029521e.png)

1. But after curl, url is in new line which throws error. Either it has to be single line or there should be "\" after curl
2. I see $ in all places for mac. It is not really required for copy pasting.

**Comment by samarthdd** [comment]
Second issue is

replace python -v , python -V or python --version ( caps matters. )

**Comment by Kirsten-Osborn** [comment]
@samarthdd I've updated 6.2.1 with the copy and paste instruction, updated python -v to python -V and removed the line break in documentation v0.3. I've left $, as this is a lower to address.

**Comment by samarthdd** [comment]
@Kirsten-Osborn this is fixed now
