### ISSUE TITLE
6.3.2 error

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/test-installation-documentation#19]
1. This steps missing context

2. Add brief description for each step

3 Repo is not easily accessible.

4. Need to add git clone command

5. terraform init, plan etc commands needs to be highlighted or put it in next line

6. terrform plan giving error which I have posted in issue chat

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/103994585-354f7280-51bd-11eb-9724-3559eda4b73f.png)

**Comment by GINAGC** [comment]
Merging with https://github.com/k8-proxy/test-installation-documentation/issues/16
