### ISSUE TITLE
6.2.1	Install Python 3 

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/test-installation-documentation#2]
Current Steps not working with Centos
Suggested Steps for Centos
``` centos
sudo yum update -y
sudo yum install -y python3
```

**Comment by MaNe2020** [comment]
@dpatel7 in some cases python3 comes already installed
I would first verify if that is the case and 
`python3 --version`
if not use the steps you suggested.
And after installation also verify with above if it is installed successfully.

**Comment by Kirsten-Osborn** [comment]
Centos steps added to 6.2.1 in documentation v0.2

**Comment by MaNe2020** [comment]
@dpatel7 this is added now. So issue can be closed.
FYI there is issue #23 that indicates possible issues while installing this.
