### ISSUE TITLE
Error in step 6.3.2

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/test-installation-documentation#20]
terraform plan giving error which I have posted in issue chat

![image](https://user-images.githubusercontent.com/64204445/103996530-fd95fa00-51bf-11eb-99df-05dd737a002b.png)

**Comment by GINAGC** [comment]
From tester: 

1. This steps missing context
2. Add brief description for each step
3. Repo is not easily accessible.
4. Need to add git clone command
5. terraform init, plan etc commands needs to be highlighted or put it in next line
6. terrform plan giving error which I have posted in issue chat

**Comment by GINAGC** [comment]
merging with https://github.com/k8-proxy/test-installation-documentation/issues/19
