### ISSUE TITLE
6.3.1 Configure tfvars

### ISSUE THREAD

**Issue by svf97** [k8-proxy/test-installation-documentation#22]
- `git clone https://github.com/filetrust/Glasswall-ICAP-Platform`
- `cd environments/installer`
- it's unclear in the documentation if the content of common.tfvars is the list of variables given or not, either ways, when running 
`terraform apply -var-file="common.tfvars", I get the following error
```
Error: No configuration files

Apply requires configuration to be present. Applying without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run 'terraform destroy' instead.

```

**Comment by Kirsten-Osborn** [comment]
@svf97 this is a duplication of #25 - please see comments on that issue

**Comment by GINAGC** [comment]
Closing as duplicated with https://github.com/k8-proxy/test-installation-documentation/issues/25
