### ISSUE TITLE
6.2.1 - refactoring of command

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/test-installation-documentation#24]
Refactor below
6.2.1 say copy paste below command

![image](https://user-images.githubusercontent.com/64204445/104585456-09832f80-568a-11eb-9cde-28ef6029521e.png)

1. But after curl, url is in new line which throws error. Either it has to be single line or there should be "\" after curl

2. Replace python -v , python -V or python --version ( caps matters. )

**Comment by Kirsten-Osborn** [comment]
@samarthdd 1 and 2 have been updated in documentation v0.3

**Comment by GINAGC** [comment]
Moving to QA to be tested in v0.3

**Comment by samarthdd** [comment]
@Kirsten-Osborn  this is Fixed now
