### ISSUE TITLE
5 Pre-requisites: Missing 6.3 section

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/test-installation-documentation#27]
Section 6.3 is missing from prerequisites.

**Comment by Kirsten-Osborn** [comment]
@MaNe2020 do you mean the code required for 6.3? This is covered in the following pre-req: 

Provided by Glasswall: 
Installation Terraform codebase 

If you mean something else, let me know

**Comment by MaNe2020** [comment]
@Kirsten-Osborn in that case can we just add (6.3 section) next to the "Installation Terraform codebase"?
That way it is clearer to what exactly this refers to.

**Comment by Kirsten-Osborn** [comment]
@MaNe2020 section 6.3 heading updated in v0.3 to explicitly reference the TF codebase, and avoid confusion

**Comment by MaNe2020** [comment]
Section 6.3 has the reference to Terraform Codebase so closing this one.
