### ISSUE TITLE
6.3.1 Configure tfvars (optional)

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/test-installation-documentation#28]
Seems out of context.
Short description should be added. 

Smth like : `.tfvars files`, are variable definitions, specified on the command line or automatically loaded.

Rest should follow.

**Comment by MaNe2020** [comment]
Also step `git clone https://github.com/filetrust/Glasswall-ICAP-Platform.git` should be added before setting up anything from this section.

**Comment by GINAGC** [comment]
merging with https://github.com/k8-proxy/test-installation-documentation/issues/25
