### ISSUE TITLE
6.3.2 Create Azure Storage: Add details to how and where to get azure account details

### ISSUE THREAD

**Issue by MaNe2020** [k8-proxy/test-installation-documentation#29]
Following
```
Before you begin you will need the following details and a valid azure login account. Once you've executed az login you will need the following information.
    organisation = "" # this just needs to be a short identifier (i.e gw)
    environment  = "" # can be anything short to identify this stacks change management tier
    azure_region = "" # which azure region do you want to use?
    tenant_id = "" # this is based on your azure account
    subscription_id = "" # this is based on your azure account
```

should be rephrased. 

It should be specified that after the `az login` tenant_id will be desplayed. And should be taken from that output and used in step that follows.
Also, few azure_region valid example stings (eg. ukwest, uksouth..) can be added also.

Command `az login` can be replaced with  `az login -u johndoe@contoso.com -p VerySecret`
Depends what better works for customer.
As first one requires browser interface.

**Comment by Lestat06** [comment]
@MaNe2020 can you tell me where did you get the subscription id?

**Comment by MaNe2020** [comment]
@Lestat06 when the id you get when running `az login` is actually subscription_id.
Also you can find it on your Azure Account UI.
Search for subscription_id and smth will show up.

**Comment by Kirsten-Osborn** [comment]
Updated in v0.3

**Comment by MaNe2020** [comment]
Details are added as part of 6.3.2.
Closing this one.
