### ISSUE TITLE
6.2.3	Update Bash to version 5

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/test-installation-documentation#3]
Current Steps not Compatible with Centos 
Suggested Steps
```centos
sudo yum -y groupinstall "Development Tools"
sudo yum install -y wget unzip
wget https://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz
tar xvf bash-5.0.tar.gz
cd bash-5.0
sudo ./configure
sudo make
sudo make install
```

**Comment by Lestat06** [comment]
The current steps worked fine for me. I just put a `-` before `xvf`.
basically changed` tar xvf bash-5.0.tar.gz` to `tar -xvf bash-5.0.tar.gz`

**Comment by Kirsten-Osborn** [comment]
@dpatel7  @Lestat06  Centos steps added to 6.2.3 in documentation v0.2

**Comment by MaNe2020** [comment]
@Kirsten-Osborn 

- step `cd bash-5.0` should be replaced with `cd bash-5.0\`
- I run `bash --version` before and after the change to 5.0 and was getting the same value 4.4.19.
@dpatel7 @Lestat06 can you please double check if the bash version is changed after the steps are done.

![image](https://user-images.githubusercontent.com/70108899/104599857-92916b00-5678-11eb-97c2-772029282046.png)

**Comment by Lestat06** [comment]
> @Kirsten-Osborn
> 
> * step `cd bash-5.0` should be replaced with `cd bash-5.0\`
> * I run `bash --version` before and after the change to 5.0 and was getting the same value 4.4.19.
>   @dpatel7 @Lestat06 can you please double check if the bash version is changed after the steps are done.
> 
> ![image](https://user-images.githubusercontent.com/70108899/104599857-92916b00-5678-11eb-97c2-772029282046.png)

@MaNe2020 just run the steps as they are on documentation. No issues and bash version remained the same!!
Try running a `sudo yum update bash`

**Comment by MaNe2020** [comment]
@Lestat06 thanks. This did the trick.

@Kirsten-Osborn one more step `sudo yum update bash` needs to be added here.

**Comment by Kirsten-Osborn** [comment]
Updated in v0.3

**Comment by Lestat06** [comment]
Change `cd bash-5.0\`    to    `cd bash-5.0`  
as `cd bash-5.0\` gives error following the next command

**Comment by MaNe2020** [comment]
@Lestat06 @Kirsten-Osborn 
it should be forward slash

so it works also with `cd bash-5.0/`

**Comment by GINAGC** [comment]
sending back just for the small modification @Kirsten-Osborn

**Comment by Kirsten-Osborn** [comment]
Updated in v0.4 to cd bash-5.0/ - happy to close without retesting
