### ISSUE TITLE
4.2 Hyperlink Issue

### ISSUE THREAD

**Issue by svf97** [k8-proxy/test-installation-documentation#32]
Hyperlink redirects to the following page

![image](https://user-images.githubusercontent.com/60857664/104692044-f3b84d80-570f-11eb-9496-e677ff37238e.png)

**Comment by Kirsten-Osborn** [comment]
@svf97 improved explanation added to 4.2 in v0.3

**Comment by MaNe2020** [comment]
@Kirsten-Osborn @svf97 
This hyperlinks are still pointing to XML pages.
If `releases.rancher.com` is just a reference to server I suppose hyperlink should be removed as it is not needed.

**Comment by svf97** [comment]
@MaNe2020 but the elaboration as to how it is required solves this? i.e. the hyperlink itself on a UI isn't the goal, rather the fact that the user machine should be allowed access to download requirements from that hyperlink and all its peripherals

**Comment by MaNe2020** [comment]
Then it should be unlinked.
Maybe bold the wording, but without the link as the link itself does not point to anything of use.
It's rather host reference.

**Comment by Kirsten-Osborn** [comment]
Updated in v0.4 - no need to re-test
