### ISSUE TITLE
6.3.5 Deploy Rancher Server 

### ISSUE THREAD

**Issue by svf97** [k8-proxy/test-installation-documentation#36]
- Filling out the "rancher server" module from the video as it is not clear in the documentation where to get `dns_zone_name`
![image](https://user-images.githubusercontent.com/60857664/104701044-c1ade800-571d-11eb-995e-41d62e799cf0.png)

- `terraform init` worked but got this error when running `terraform plan`
![image](https://user-images.githubusercontent.com/60857664/104701002-b0fd7200-571d-11eb-9080-c18765d0e528.png)

**Comment by GINAGC** [comment]
Closing as duplicated with https://github.com/k8-proxy/test-installation-documentation/issues/31
