### ISSUE TITLE
6.3.7- Error running terraform apply

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/test-installation-documentation#40]
Description is not clear

cd environments/main/rancher-clurser is not mentioned
terraform init throws error

![image](https://user-images.githubusercontent.com/64204445/104712341-70671e00-5748-11eb-9b5d-6e8641c9c235.png)

terraform apply throws error

![image](https://user-images.githubusercontent.com/64204445/104712354-73620e80-5748-11eb-978b-e3e0aad18ac5.png)

**Comment by GINAGC** [comment]
duplicated with https://github.com/k8-proxy/test-installation-documentation/issues/38
