### ISSUE TITLE
6.2.7 Install Azure CLI - Step 1

### ISSUE THREAD

**Issue by kerempg** [k8-proxy/test-installation-documentation#42]
6.2.7 Install Azure CLI

For step 1: 
`brew install azure-cli`

Below warning & error message is given:

**Warning**: You are using macOS 10.13.
 We (and Apple) do not provide support for this old version.
 You will encounter build failures with some formulae.
 Please create pull requests instead of asking for help on Homebrew's GitHub,
 Twitter or any other official channels. You are responsible for resolving
 any issues you experience while you are running this
 old version.
 **Error**: azure-cli: no bottle available!
 You can try to install from source with:
  brew install --build-from-source azure-cli
 Please note building from source is unsupported. You will encounter build
 failures with some formulae. If you experience any issues please create pull
 requests instead of asking for help on Homebrew's GitHub, Twitter or any other
 official channels.

I was able to install it via
`brew install --build-from-source azure-cli`

**Comment by Kirsten-Osborn** [comment]
Workaround added to v0.3
