### ISSUE TITLE
6.2.4	Install Git

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/test-installation-documentation#5]
Current Steps are not compatible with Centos 
Suggested steps
```centos
sudo yum install git
```
or if require specific version 
```centos
wget https://github.com/git/git/archive/v2.1.2.tar.gz -O git.tar.gz
tar -zxf git.tar.gz
cd git-*
make configure
./configure --prefix=/usr/local
make install
git --version
```

**Comment by Kirsten-Osborn** [comment]
@dpatel7 Centos steps added to documentation v0.2. I'm not aware that a specific version is required - we reviewed all the tool versions required, and specified this in section 5 where the version was important - there's no version number against Git.

**Comment by MaNe2020** [comment]
@Kirsten-Osborn can we add also verification step for Centos as done for MAC.
In general this would be great to have across all steps, as a way to verify installation.

**Comment by Kirsten-Osborn** [comment]
Updated in v0.3

**Comment by MaNe2020** [comment]
This is added in v0.3.
Verification is also present for the rest of the steps. 
Closing the issue. @GINAGC @dpatel7
