### ISSUE TITLE
6.2.5	Install Terraform

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/test-installation-documentation#6]
Current Steps are not compatible with Centos
Suggested steps
```centos
wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
unzip ./terraform_0.14.3_linux_amd64.zip 
mv terraform /usr/local/bin/
terraform –v
rm -f ./terraform_0.14.3_linux_amd64.zip
```

**Comment by MaNe2020** [comment]
From terraform official page, again not sure what is the difference:
= Install Terraform
```
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
sudo yum -y install terraform
```
= Verify installation
`terraform -help`

**Comment by Kirsten-Osborn** [comment]
@dpatel7 @MaNe2020 Centos steps added to documentation v0.2

**Comment by MaNe2020** [comment]
@Kirsten-Osborn 
Can we change 
= Verify installation
`terraform -help` to `terraform -version`

**Comment by GINAGC** [comment]
closing with https://github.com/k8-proxy/test-installation-documentation/issues/30 which has the same request that Marija added here
