### ISSUE TITLE
6.2.7	Install Azure CLI

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/test-installation-documentation#8]
Current Steps are not compatible with Centos
Suggested steps
```centos
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo
sudo yum install -y azure-cli
```

**Comment by MaNe2020** [comment]
To verify installation:

`az --version`

**Comment by Kirsten-Osborn** [comment]
@dpatel7 @MaNe2020 Centos steps added to documentation v0.2

**Comment by Lestat06** [comment]
creating service principal from centOS gave me `Role assignemt creation filed` while on my azure account I can see the the principal is created. Did anyone else run into this?
![6 2 7](https://user-images.githubusercontent.com/6232283/104512780-0424d700-55ef-11eb-810c-6b38e34ff188.PNG)

**Comment by MaNe2020** [comment]
@Kirsten-Osborn can we split this screenshot in documentation?
It is not clear where one step ends and another one starts.

**Comment by Kirsten-Osborn** [comment]
We are now addressing the azure service principal as a pre-req rather than providing instructions in 6.1, so this can be closed
